name: volleyball_rotations
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.0
  firebase_core: ^0.4.2+1
  firebase_auth: ^0.15.0+1
  cloud_firestore: ^0.12.10+2
  toast: ^0.1.5
  modal_progress_hud: ^0.1.3
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
